# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='teamid',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workout',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='workoutid',
        ),
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='weights',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_id',
            field=models.CharField(default=uuid.UUID('2f3b2366-5a78-44d8-a8e7-beac123cdd22'), max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='distancepoints',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weightpoints',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='workout',
            name='picture',
            field=models.ImageField(blank=True, upload_to='workout_images'),
        ),
        migrations.AddField(
            model_name='workout',
            name='workoutType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rango.WorkoutType'),
        ),
    ]
