# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20180322_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_id',
            field=models.CharField(default=uuid.UUID('6c4413f4-5a45-4f1d-ba95-b47208c57c60'), max_length=12, unique=True),
        ),
    ]
