# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20180322_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_id',
            field=models.CharField(default=uuid.UUID('4f2c36de-fc61-4be9-8f1e-af6684fbde90'), max_length=12, unique=True),
        ),
    ]
