# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20180322_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_id',
            field=models.CharField(default=uuid.UUID('a8154b29-3eed-44e9-9a0b-de083de53eff'), max_length=12, unique=True),
        ),
    ]
