# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20180322_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_id',
            field=models.CharField(default=uuid.UUID('2aff0d27-19d2-42d3-839b-1c8427bfe21a'), max_length=12, unique=True),
        ),
    ]
