# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_auto_20180328_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_id',
            field=models.CharField(default=uuid.UUID('4d877660-65db-4b9f-a7df-36b323d66e49'), max_length=12, unique=True),
        ),
    ]
