# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_auto_20180328_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_id',
            field=models.CharField(default=uuid.UUID('26d4e7c4-7387-4139-be0b-7a8df5914d81'), max_length=12, unique=True),
        ),
    ]
